task: 'people_snapshot'
subject: 'female-6-plaza'
experiment: 'single-gpu'

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'female-6-plaza_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'female-6-plaza_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'female-6-plaza_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'female-6-plaza_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'female-6-plaza_test'

eval_cam:
  dataset_module: 'core.data.human_nerf.eval_cam'
  dataset: 'female-6-plaza_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 0.5
render_frames: 9

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 24
