task: 'h36m_multiview'
subject: 'S6'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S6_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S6_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S6_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'h36m_S6_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'h36m_S6_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 0.5
patch:
    size: 24
