task: 'zju_mocap'
subject: 'p390'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_390_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_390_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_390_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_390_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_390_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 1.
render_frames: 9
topview_camera:
  h: 1.
  r: 0.5
