task: 'h36m_multiview'
subject: 'S8'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S8_train'
  maxiter: 200000
  lrate_decay: 200

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S8_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S8_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'h36m_S8_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'h36m_S8_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 1
render_frames: 9

patch:
    N_patches: 8
bbox_offset: 0.5
