task: 'h36m_multiview'
subject: 'S8'
action: 'WalkTogether'
experiment: 'adventure'
logdir: 'experiments/human_nerf/h36m_multiview/S8/adventure/'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S8_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S8_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S8_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'h36m_S8_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'h36m_S8_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 0.72
render_frames: 9
