task: 'h36m_multiview'
subject: 'S9'
action: 'Sitting'
experiment: 'adventure'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S9_Sitting_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S9_Sitting_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S9_Sitting_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'h36m_S9_Sitting_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'h36m_S9_Sitting_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 1. 
render_frames: 9
show_alpha: true

topview_camera:
  h: 1.2
  r: 1

