task: 'genebody'
subject: 'natacha'
experiment: 'single_gpu'

# non-rigid motion mlp
#non_rigid_motion_mlp:
#  kick_in_iter: 100000
#  full_band_iter: 200000

# pose decoder
#pose_decoder:
#  kick_in_iter: 20000

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'genebody_natacha_train'
  lr: 0.0003
  batch_size: 1
  lrate_decay: 300

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'genebody_natacha_test'
  shuffle: False

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'genebody_natacha_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'genebody_natacha_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'genebody_natacha_test'

bgcolor: [255., 255., 255.]
#bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
#render_frames: 9
patch:
    size: 24
render_frames: 9
show_alpha: true

topview_camera:
  h: 1.
  r: 0.5
