task: 'people_snapshot'
subject: 'male-5-outdoor'
experiment: 'single-gpu'

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'male-5-outdoor_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'male-5-outdoor_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'male-5-outdoor_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'male-5-outdoor_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'male-5-outdoor_test'

eval_cam:
  dataset_module: 'core.data.human_nerf.eval_cam'
  dataset: 'male-5-outdoor_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 0.474

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20