task: 'h36m'
subject: 'S1'
experiment: 'single_gpu'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S1_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S1_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S1_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'h36m_S1_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'h36m_S1_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 0.5

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
