task: 'h36m'
subject: 'S11'
experiment: 'single_gpu'
actionfolder: 'Posing'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S11_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S11_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'h36m_S11_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'h36m_S11_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'h36m_S11_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 1.0 
render_frames: 9

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
